package cli_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/panic-at/envx/internal/cli"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestExport_Dotenv(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "FOO", "bar", "--profile", "default")
	mustRun(t, cfg, "set", "BAZ", "qux", "--profile", "default")

	stdout, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--format", "dotenv")
	require.NoError(t, err)
	assert.Equal(t,
		"# Generated by envx — do not commit if contains secrets\nBAZ=qux\nFOO=bar\n",
		stdout)
}

func TestExport_DefaultFormatIsDotenv(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "FOO", "bar", "--profile", "default")

	stdout, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default")
	require.NoError(t, err)
	assert.Contains(t, stdout, "FOO=bar")
}

func TestExport_JSON(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "FOO", "bar", "--profile", "default")
	mustRun(t, cfg, "set", "BAZ", "qux", "--profile", "default")

	stdout, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--format", "json")
	require.NoError(t, err)

	var got map[string]string
	require.NoError(t, json.Unmarshal([]byte(stdout), &got))
	assert.Equal(t, map[string]string{"FOO": "bar", "BAZ": "qux"}, got)
}

func TestExport_Shell(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "FOO", "bar", "--profile", "default")

	stdout, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--format", "shell")
	require.NoError(t, err)
	assert.Contains(t, stdout, "export FOO='bar'")
}

func TestExport_OutputFile(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "FOO", "bar", "--profile", "default")
	outPath := filepath.Join(t.TempDir(), "out.env")

	stdout, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--output", outPath)
	require.NoError(t, err)
	assert.Contains(t, stdout, "Exported profile 'default'")

	data, err := os.ReadFile(outPath)
	require.NoError(t, err)
	assert.Contains(t, string(data), "FOO=bar")
}

func TestExport_OutputFileSensitiveIs0600(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "TOKEN", "s3cret", "--profile", "default", "--sensitive")
	outPath := filepath.Join(t.TempDir(), "secret.env")

	_, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--output", outPath)
	require.NoError(t, err)

	info, err := os.Stat(outPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0o600), info.Mode().Perm(),
		"an export containing sensitive variables must be written 0600")
}

func TestExport_ResolutionFailsWithoutAllowErrors(t *testing.T) {
	cfg := tempProject(t)
	// op:// is parsed but not yet resolvable, so it fails resolution.
	mustRun(t, cfg, "set", "BAD", "--ref", "op://v/i/f", "--profile", "default")

	_, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "failed to resolve")
	assert.Contains(t, err.Error(), "BAD")
}

func TestExport_ResolutionFailsWithAllowErrors(t *testing.T) {
	cfg := tempProject(t)
	mustRun(t, cfg, "set", "GOOD", "ok", "--profile", "default")
	mustRun(t, cfg, "set", "BAD", "--ref", "op://v/i/f", "--profile", "default")

	stdout, stderr, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--allow-errors")
	require.NoError(t, err)
	assert.Contains(t, stdout, "GOOD=ok")
	assert.NotContains(t, stdout, "BAD", "unresolved variables are omitted from the output")
	assert.Contains(t, stderr, "warning")
	assert.Contains(t, stderr, "BAD")
}

func TestExport_UnknownFormat(t *testing.T) {
	cfg := tempProject(t)
	_, _, err := runCmd(t, "--config", cfg, "export", "--profile", "default", "--format", "toml")
	require.Error(t, err)

	var exit *cli.ExitError
	require.ErrorAs(t, err, &exit)
	assert.Equal(t, 2, exit.Code)
}

func TestExport_ProfileNotFound(t *testing.T) {
	cfg := tempProject(t)
	_, _, err := runCmd(t, "--config", cfg, "export", "--profile", "ghost")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "does not exist")
}

func TestExport_MissingRequiredProfileFlag(t *testing.T) {
	cfg := tempProject(t)
	_, _, err := runCmd(t, "--config", cfg, "export")
	require.Error(t, err)

	var exit *cli.ExitError
	require.ErrorAs(t, err, &exit)
	assert.Equal(t, 2, exit.Code, "a missing required flag is a usage error")
}
