package exporter_test

import (
	"testing"

	"github.com/panic-at/envx/internal/exporter"
	"github.com/stretchr/testify/assert"
)

// dotenvHdr is the dotenv exporter's comment header line.
const dotenvHdr = "# Generated by envx — do not commit if contains secrets\n"

func TestDotenv_BasicFixture(t *testing.T) {
	assert.Equal(t, readFixture(t, "dotenv_basic.env"), runExport(t, exporter.FormatDotenv, basicVars))
}

func TestDotenv_SpecialCharsFixture(t *testing.T) {
	special := map[string]string{
		"GREETING": "hello world",
		"HASH":     "rgb#ffffff",
		"NEWLINE":  "line1\nline2",
		"PATHISH":  `C:\tmp\x`,
		"QUOTED":   `say "hi"`,
		"TABBED":   "a\tb",
		"UNICODE":  "café 🚀",
	}
	assert.Equal(t, readFixture(t, "dotenv_special_chars.env"),
		runExport(t, exporter.FormatDotenv, special))
}

func TestDotenv_Cases(t *testing.T) {
	tests := []struct {
		name string
		vars map[string]string
		want string
	}{
		{
			name: "empty produces header only",
			vars: map[string]string{},
			want: dotenvHdr,
		},
		{
			name: "single simple value is unquoted",
			vars: map[string]string{"FOO": "bar"},
			want: dotenvHdr + "FOO=bar\n",
		},
		{
			name: "multiple values are sorted by key",
			vars: map[string]string{"ZED": "z", "ALPHA": "a", "MID": "m"},
			want: dotenvHdr + "ALPHA=a\nMID=m\nZED=z\n",
		},
		{
			name: "empty value stays unquoted",
			vars: map[string]string{"EMPTY": ""},
			want: dotenvHdr + "EMPTY=\n",
		},
		{
			name: "value with space is quoted",
			vars: map[string]string{"K": "a b"},
			want: dotenvHdr + "K=\"a b\"\n",
		},
		{
			name: "value with hash is quoted",
			vars: map[string]string{"K": "a#b"},
			want: dotenvHdr + "K=\"a#b\"\n",
		},
		{
			name: "value with double quote is escaped",
			vars: map[string]string{"K": `a"b`},
			want: dotenvHdr + "K=\"a\\\"b\"\n",
		},
		{
			name: "value with backslash is escaped",
			vars: map[string]string{"K": `a\b`},
			want: dotenvHdr + "K=\"a\\\\b\"\n",
		},
		{
			name: "value with newline is escaped",
			vars: map[string]string{"K": "a\nb"},
			want: dotenvHdr + "K=\"a\\nb\"\n",
		},
		{
			name: "value with tab is escaped",
			vars: map[string]string{"K": "a\tb"},
			want: dotenvHdr + "K=\"a\\tb\"\n",
		},
		{
			name: "unicode value without specials is unquoted",
			vars: map[string]string{"K": "café"},
			want: dotenvHdr + "K=café\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, runExport(t, exporter.FormatDotenv, tt.vars))
		})
	}
}
