package exporter

import (
	"io"
	"strings"
)

// dotenvHeader is the comment line prepended to every dotenv export.
const dotenvHeader = "# Generated by envx — do not commit if contains secrets\n"

// dotenvSpecial is the set of characters that force a value to be quoted.
const dotenvSpecial = " #\"\\\n\r\t"

// dotenvExporter writes variables in the KEY=value dotenv format.
type dotenvExporter struct{}

// Format returns FormatDotenv.
func (dotenvExporter) Format() Format { return FormatDotenv }

// Export writes vars as dotenv lines. Values containing whitespace, '#',
// quotes or backslashes are wrapped in double quotes with the necessary
// characters escaped; simple values are written bare.
func (dotenvExporter) Export(w io.Writer, vars map[string]string) error {
	var b strings.Builder
	b.WriteString(dotenvHeader)
	for _, k := range sortedKeys(vars) {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(dotenvQuote(vars[k]))
		b.WriteByte('\n')
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// dotenvQuote returns value ready to appear on the right-hand side of a dotenv
// assignment, quoting and escaping it only when necessary.
func dotenvQuote(value string) string {
	if !strings.ContainsAny(value, dotenvSpecial) {
		return value
	}
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
