package exporter

import (
	"fmt"
	"io"
	"strings"
)

// shellHeader is the comment line prepended to every shell export.
const shellHeader = "# Generated by envx — source this file with: source <file>\n"

// shellExporter writes variables as POSIX shell export statements.
type shellExporter struct{}

// Format returns FormatShell.
func (shellExporter) Format() Format { return FormatShell }

// Export writes vars as "export KEY='value'" lines compatible with sh, bash
// and zsh. Values are single-quoted; embedded single quotes are emitted as the
// standard '\” sequence.
func (shellExporter) Export(w io.Writer, vars map[string]string) error {
	var b strings.Builder
	b.WriteString(shellHeader)
	for _, k := range sortedKeys(vars) {
		fmt.Fprintf(&b, "export %s=%s\n", k, shellQuote(vars[k]))
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// shellQuote single-quotes value for safe use in a POSIX shell, escaping any
// embedded single quote as '\”.
func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
