package exporter_test

import (
	"testing"

	"github.com/panic-at/envx/internal/exporter"
	"github.com/stretchr/testify/assert"
)

// shellHdr is the shell exporter's comment header line.
const shellHdr = "# Generated by envx — source this file with: source <file>\n"

func TestShell_BasicFixture(t *testing.T) {
	assert.Equal(t, readFixture(t, "shell_basic.sh"), runExport(t, exporter.FormatShell, basicVars))
}

func TestShell_Cases(t *testing.T) {
	tests := []struct {
		name string
		vars map[string]string
		want string
	}{
		{
			name: "empty produces header only",
			vars: map[string]string{},
			want: shellHdr,
		},
		{
			name: "single value is single-quoted",
			vars: map[string]string{"FOO": "bar"},
			want: shellHdr + "export FOO='bar'\n",
		},
		{
			name: "multiple values are sorted by key",
			vars: map[string]string{"ZED": "z", "ALPHA": "a"},
			want: shellHdr + "export ALPHA='a'\nexport ZED='z'\n",
		},
		{
			name: "empty value",
			vars: map[string]string{"K": ""},
			want: shellHdr + "export K=''\n",
		},
		{
			name: "value with space",
			vars: map[string]string{"K": "a b"},
			want: shellHdr + "export K='a b'\n",
		},
		{
			name: "value with single quote uses the close-escape-reopen sequence",
			vars: map[string]string{"K": "it's"},
			want: shellHdr + `export K='it'\''s'` + "\n",
		},
		{
			name: "value with multiple single quotes",
			vars: map[string]string{"K": "a'b'c"},
			want: shellHdr + `export K='a'\''b'\''c'` + "\n",
		},
		{
			name: "value with double quote is left as-is inside single quotes",
			vars: map[string]string{"K": `say "hi"`},
			want: shellHdr + `export K='say "hi"'` + "\n",
		},
		{
			name: "unicode value",
			vars: map[string]string{"K": "café 🚀"},
			want: shellHdr + "export K='café 🚀'\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, runExport(t, exporter.FormatShell, tt.vars))
		})
	}
}
